/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tw.edu.sju.ee.eea.module.fra.file.fr;

import tw.edu.sju.ee.eea.core.frequency.response.FrequencyResponseConfig;
import javax.swing.JPanel;
import org.openide.util.NbBundle.Messages;

@Messages({
    "FrVisualPanel1_displayName=Frequency Response Configuration"
})
public final class FrVisualPanel1 extends JPanel {

    /**
     * Creates new form FrVisualPanel1
     */
    public FrVisualPanel1() {
        initComponents();
    }

    @Override
    public String getName() {
        return "#FrVisualPanel1_displayName";
    }
    
    public FrequencyResponseConfig getConfig() {
        return frequencyResponseConfigPane1.getConfig();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frequencyResponseConfigPane1 = new tw.edu.sju.ee.eea.ui.swing.pane.FrequencyResponseConfigPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frequencyResponseConfigPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frequencyResponseConfigPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tw.edu.sju.ee.eea.ui.swing.pane.FrequencyResponseConfigPane frequencyResponseConfigPane1;
    // End of variables declaration//GEN-END:variables
}
